week4: 4차 필수과제 진행 (xml)
NOW-SOPT-ANDROID/junseo-choi pull request #10
Opened 2024-04-28 15:30 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #9

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- api 열심히 붙여봤습니다
- 로그아웃, 비밀번호 변경 기능 추가했습니다

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/junseo-choi/assets/127238018/492ddf1f-6f76-411e-adbf-ed09813bf1be

https://github.com/NOW-SOPT-ANDROID/junseo-choi/assets/127238018/6953f613-bbb1-4ea8-9816-dfa9bb1c015f

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
코루틴도 조금 사용했구, 기존에 사용한 Room은 다 날렸습니다.
BaseResponse를 쓸까 했지만 일반적으로 저렇게 다 똑같이 날라오지는 않을거같아서 그냥 배제했습니다

2024-05-05 00:40 UTC, arinming reviewed
신경쓰셔서 열심히 하신게 느껴지네용.. 수고하셨습니따

2024-05-05 00:40 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +    private var userId: Int = 0
여기서 lateinit이나 by lazy를 쓰지 않고 바로 초기화하신 이유가 궁금합니답

2024-05-05 00:40 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +        getUserId()
단순 궁금한 건데, onCreate에서 API를 호출하는 거랑 onStart, onResume에서나 getUserId를 호출하는 것 중 onCreate 성능이 더 괜찮은가욤?

2024-05-05 00:40 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
>          mainViewModel = ViewModelProvider(this, factory)[MainViewModel::class.java]
우와 뷰모델을 이렇게 초기화 할 수도 있군요

2024-05-05 00:40 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
>              }
유저 아이디를 성공적으로 받아온 뒤에 친구 프로필을 불러오는 순서 배워갑니다!

2024-05-05 00:40 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/main/home/HomeFragment.kt
>          getUserInfo()
MainActivity에서 이미 getUserInfo를 하셨는데 다시 호출하신 이유가 있나용?

2024-05-05 00:40 UTC, arinming commented on app/src/main/java/com/sopt/now/ui/main/myPage/MyPageFragment.kt
>      }
userId가 0인 회원이 있으면 어떻게 되나영...?!!

2024-05-05 08:49 UTC, yeonjeen reviewed
역시 배울 점 많이 줍줍하고 갑니당~ 수고 많으셨어요:)

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/data/NetworkModule.kt
> +
이 함수는 어떤 용도인가용?

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
>          mainViewModel = ViewModelProvider(this, factory)[MainViewModel::class.java]
오.. 저도 알아갑니당

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/main/MainViewModel.kt
> +    }
코루틴으로 비동기처리... 짱

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/main/myPage/MyPageFragment.kt
> +        requireActivity().finish()
requireActivity() 저 처음(?) 봐요

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/passwordChange/PasswordChangeActivity.kt
> +    private lateinit var passwordChangeViewModel: PasswordChangeViewModel
나중에 초기화 되면 null 예외가 발생할 수 있지 않을까요?

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/passwordChange/PasswordChangeActivity.kt
> +    }
by viewModels()등이 아니라 baseFactory를 이용해서 ViewModel을 생성하시는 이유가 있으실까요?

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ui/passwordChange/PasswordChangeActivity.kt
> +}
비밀번호 변경 시 에러처리 로직도 추가 되면 좋을 것 같아요~

2024-05-05 08:49 UTC, yeonjeen commented on app/src/main/res/layout/activity_password_change.xml
> +        <com.google.android.material.textfield.TextInputLayout
오... 처음보는 위젯이네여 저도 담에 한 번 써봐야겠어요

2024-05-05 11:08 UTC, SYAAINN reviewed
호... 확실히 코드 퀄리티가 높아서 이해하는데 쉽지 않았지만 더욱 더 공부해보겠습니다 !

2024-05-05 11:08 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/remote/response/GetUserResponse.kt
> +    }
오오.. companion object에 대해 더 공부해봐야겠네요

2024-05-05 11:08 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/remote/response/GetUserResponse.kt
> +    val data: User? = defaultUser,
초기화를 companion object를 통해 따로 만들어서 하셨네요!

2024-05-05 11:08 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/remote/service/UserService.kt
> +}
AuthService 랑 Userservice 가 분리되어 있는 디테일 ..! 참고하겠습니다

2024-05-05 11:08 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
>          mainViewModel = ViewModelProvider(this, factory)[MainViewModel::class.java]
뭔가 .. intent랑 닮아있는 느낌도 드는거 같아요

2024-05-05 11:08 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
>      class MineViewHolder private constructor(
private constructor 처음 보는 친구 발견..! 공부해봐야겠네요. 혹시 간단한 역할 설명 가능할까요?

2024-05-05 11:08 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/remote/service/AuthService.kt
> +    suspend fun signUp(
suspend fun으로 선언하신 이유가 있나요?!

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/NetworkModule.kt
> +
서버통신시 인터셉터를 통해 서버에서 오는 내용을 로그로 남겨줍니다!!

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/remote/service/AuthService.kt
> +    suspend fun signUp(
일시중단되고 실행되는 함수를 말합니다...! 이 부분은 오늘 저녁에 진행되는 산군의 미미나를 확인해보시죠 😁

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +    private var userId: Int = 0
기존에 쓰던 친구들이 마이그레이션이 덜되었습니다...! 😅

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
>      class MineViewHolder private constructor(
음 constructor란 생성자를 말하는데요,,,! MineViewHolder의 내용물을 지정해주고 생성해주는 역할을 합니다 ‼️
자세한 사항은 구글에 constructor in kotlin을 검색해보셔요 😁

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeFragment.kt
>          getUserInfo()
MainActivity에서는 유저 id만을 가져오고 있습니다,,,!

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/myPage/MyPageFragment.kt
> +        requireActivity().finish()
activity를 불러올 때 null 안정성을 챙겨주는 친구라고 알고 있슴둥

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/myPage/MyPageFragment.kt
>      }
0인 유저가 없더라구요,,,! 서버에서 1부터 시작하는 것 같았습니당

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/passwordChange/PasswordChangeActivity.kt
> +}
이미 에러 메시지가 출력되도록 구현되어 있습니다,,!

2024-05-07 07:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +        getUserId()
음,,, 어떤 생명주기에 호출해야 하는지에 따라 다를 것 같아요,,,! 목적과 용도에 따라?!

2024-05-09 17:28 UTC, briandr97 requested changes
안녕하세요 준서님, 준서님의 리뷰어를 맡게된 권용민이라고 합니다!

필수 과제에 xml과 compose가 있는데요 xml은 제가, compose는 준원님께서 리뷰해주실 예정입니다.
코드에 정답이 없으며, 저희 또한 많이 부족한 사람이므로 공통 로직에서 저와 준원님의 의견이 상충될 수 있습니다. 혹시 그런 상황이 발생한다면, 준서님께서 생각하시는대로 진행하고 말씀해주시면 됩니다!

또 제가 리뷰해드린 내용이라고 해서 정답은 아닙니다. 사람마다 생각이 다를 수 있으며, 제가 틀렸을 수도 있습니다. 납득이 되지 않으면 언제든 질문주시고, 준서님의 생각을 말씀해주세요!

과제하느라 고생하셨습니다! 잘부탁드립니다!

모든 리뷰에 1~5에 해당하는 번호를 남겼습니다. 해당 번호들은 중요도를 나타냅니다.
1,2번은 changes requested,
3번은 comment,
4,5번은 추가정보 정도로 생각해주시면 좋을 것 같습니다.

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/data/NetworkModule.kt
> +    val userService = NetworkModule.create<UserService>(BuildConfig.AUTH_BASE_URL)
[2]
baseUrl이 같은 것 같은데 두 개를 만드신 이유가 있을까요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/data/remote/response/GetFriendsResponse.kt
> +    val `data`: List<Data>,
[3]
이 친구는 왜 백틱이 달려있을까요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/data/remote/response/GetUserResponse.kt
> +            )
[5]
유저에 대한 로직이라면 User의 동반객체에 위치시키는건 어떻게 생각하시나요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +    private val mainViewModel: MainViewModel by lazy { MainViewModel() }
[1]
MainViewModel이 AAC ViewModel을 상속 받고 있는데, 그 이유가 뭘까요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> -        mainViewModel = ViewModelProvider(this, factory)[MainViewModel::class.java]
[1]
이 코드는 왜 지워졌나요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
>                  executePendingBindings()
[3]
이 함수를 사용한 이유는 무엇일까요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
> +    private var friendList: List<GetFriendsResponse.Data> = emptyList()
[2]
`ListAdapter`를 쓰셨는데 `getItem(position: Int)` 함수를 이용하지 않고 따로 리스트를 만들어서 사용하신 이유가 있을까요?

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
> +    private var friendList: List<GetFriendsResponse.Data> = emptyList()
[2]
변수 네이밍을 자료구조에 의존적으로 하는 것은 개인적으로는 좋지 않다고 생각합니다.
자료구조가 변경되었을때 변수명도 변경되어야하기 때문이죠.
저는 friendList 대신 friends라고 할 것 같습니다. 

(물론 자료구조가 변경될 일이 얼마나 있냐 라고 하실 수도 있습니다. 선호되는 방향으로 선택해주세요!)

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/myPage/MyPageFragment.kt
> +        requireActivity().finish()
[3]
```kotlin
@NonNull
public final FragmentActivity requireActivity() {
    FragmentActivity activity = getActivity();
    if (activity == null) {
        throw new IllegalStateException("Fragment " + this + " not attached to an activity.");
    }
    return activity;
}
```

`activity`는 nullable한 객체를 반환해주고 `requireActivity`는 NonNull인 객체를 반환합니다.
다만 `requireActivity`는 null인 경우 예외를 던져서 터트립니다.
물론 null이 발생하는 경우가 별로 없지만 모든 상황에 대처해야한다면 `activity`를 사용하시면 됩니다.

2024-05-09 17:28 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ui/main/myPage/MyPageFragment.kt
>      }
[5]
mysql에서 auto_increament되는 id가 1부터 시작해서 일반적으로 0번은 없긴 합니다. 물론 저도 백엔드는 잘 모릅니다. 참고만 해주세요.

2024-05-10 06:49 UTC, junseo511 reviewed
뭔가 막힌 부분이 뚫린 느낌이네요!! 꼼꼼한 리뷰 감사합니다 ☺️

앞으로도 잘부탁드려요 👍

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/remote/response/GetFriendsResponse.kt
> +    val `data`: List<Data>,
data는 이미 사용되는 변수명이라 백틱을 넣어서 사용해야 한다고 알고 있습니다!!

근데 사실 JSON to Kotlin Class를 사용했어요 🤣

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/remote/response/GetUserResponse.kt
> +            )
아!! 맞네요 그렇게 해놓은줄 알았는데 아니었네요 (~머쓱~)

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +    private val mainViewModel: MainViewModel by lazy { MainViewModel() }
저 안그래도 이즈리얼 하시면서 혼냈다고 들었습니다 🤣

덕분에 세훈이형한테도 이중혼남 이슈 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> +    private val mainViewModel: MainViewModel by lazy { MainViewModel() }
아 근데 ViewModelProvider로 쓰면 되나요? 원래 저번주까지는 뷰모델팩토리를 만들어서 썼었는데 🤔

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/MainActivity.kt
> -        mainViewModel = ViewModelProvider(this, factory)[MainViewModel::class.java]
룸 날리면서 다같이 날려버렷어요,,,🥺

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
> +    private var friendList: List<GetFriendsResponse.Data> = emptyList()
아 네이밍은 저도 friends를 선호하는 편인데 List로 해버렸네요!! 저도 그렇게 생각하는 편이라 :)
PRND 컨벤션도 아마 이걸 따르는걸로 알고 있슴당!!

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
>                  executePendingBindings()
데이터바인딩으로 뷰홀더를 사용하고자 사용했습니다...!

2024-05-10 06:49 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
> +    private var friendList: List<GetFriendsResponse.Data> = emptyList()
와...! 안그래도 자꾸 터져서 왜 터지나 했더니 여기가 문제였군요 🥺 감사합니다

2024-05-23 08:01 UTC, SYAAINN reviewed
전체적으로 코드 리팩토링이 깔끔해진 것 같습니다! 수고하셨어요

2024-05-23 08:01 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/NetworkModule.kt
> +        }
이 부분의 역할이 궁금합니다!

2024-05-23 08:01 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/remote/response/SignInResponse.kt
> +    val status: Int,
code 와 status 가 이름이 다른 이유가 있을까요?

2024-05-23 08:01 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ui/main/home/HomeAdapter.kt
> +            is FriendViewHolder -> if (item is HomeItem.FriendItem) holder.bind(item.friend)
내 프로필과 친구 프로필을 이렇게도 구분할 수 있군요!

2024-05-23 10:37 UTC, arinming approved these changes

2024-05-23 20:14 UTC, yeonjeen approved these changes

2024-05-24 05:04 UTC, merged