week4: 4차 필수과제 진행 (compose)
NOW-SOPT-ANDROID/junseo-choi pull request #12
Opened 2024-05-02 19:11 UTC by junseo511

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #11

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- api 열심히 붙여봤습니다
- 함수 정리를 조금 해봤습니다
- argument 전달 부분을 개선해봤습니다

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/junseo-choi/assets/127238018/5f38e89c-952d-44ab-a195-066d8877cb7c

https://github.com/NOW-SOPT-ANDROID/junseo-choi/assets/127238018/e64c72d7-ba72-457e-bfcb-736b9e5b0498

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
항상 욕심은 있지만 결과물은 크게 만족스럽진 못한 컴포즈네요 ㅠㅠ
그래도 열심히 해봤습니다!!

2024-05-05 00:51 UTC, arinming reviewed
수고하셨습니당 가독성 너무 조하요

2024-05-05 00:51 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +            .client(okHttpClient)
baseUrl이랑 FriendUrl을 통일해서 한 함수로 만드셨네용 배워갑니다!!!!

2024-05-05 00:51 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +    val `data`: List<Data>,
여기에 따옴표를 쓰신 이유가 궁금합니댜

2024-05-05 00:51 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +        )[MainViewModel::class.java]
ViewModel을 이렇게 초기화 하는 방법도 있네요!
저는 HomeScreen 파라미터로 바로 뷰모델을 초기화했는데 간결하구 좋은 것 같아요 ㅎㅎ 한 번 참고해보셔도 좋을 것 같아영

2024-05-05 00:51 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/feature/signUp/SignUpScreen.kt
> +                )
증말 확실히 컴포즈 가독성이 레전드네여

2024-05-05 14:45 UTC, yeonjeen reviewed
수고 많으셨습니다~

2024-05-05 14:45 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +fun ProfilePicture(url: String) {
오 순수한 궁금증인데 이미지가 아니라 픽처라고 하신 이유가 있으신가요?

2024-05-05 14:45 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/feature/myPage/MyPageScreen.kt
> +    AsyncImage(
오 처음 보는 친구인데 이 친구의 장점은 뭔가요?

2024-05-05 14:45 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/feature/signIn/SignInScreen.kt
> +        )[MainViewModel::class.java]
뷰모델 생성 시 BaseFactory를 자주 사용하시는 것 같은데 이렇게 생성 했을 때의 이점이 있나요??

2024-05-05 14:45 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/feature/signUp/SignUpViewModel.kt
> +
거의 모든 파일에 모든 코드가 일관되게 있어서 가독성이 좋은 것 같아용

2024-05-05 14:49 UTC, SYAAINN commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
이 친구 기능이 궁금합니다..!

2024-05-05 14:49 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +    val `data`: List<Data>,
예리한 지적..!

2024-05-05 14:49 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/data/remote/response/SignInResponse.kt
> +    val status: Int,
저도 이걸 status로 작성했는데 code로 바꾸면 좀 더 통일감이 있을것 같습니다!

2024-05-05 14:49 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/feature/common/base/BaseFactory.kt
> +package com.sopt.now.compose.feature.common.base
우와.. 어려운 친구 하나 등장..! Base 파일에 대해 알아 봐야할 것 같아요

2024-05-05 14:49 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +        private const val DEFAULT_FRIEND_PAGE = 1
상수를 허용하지 않는 치밀한 모습 ㅋㅋㅋㅋㅋ 최고

2024-05-05 14:49 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/compose/feature/signUp/SignUpScreen.kt
> +                )
진짜 깔끔,, 쓰기도 보기도 좋은게 컴포즈가 유혹하는 것 같아요

2024-05-05 19:07 UTC, murjune requested changes
안녕하세요. 준서님 리뷰어로 함께하게 된 명예OB 이준원입니다. 앞으로 잘 부탁드립니다.

양이 상당히 많았을 텐데 과제 구현하시느라 고생하셨습니다!  
코드를 읽다가 상세한 리뷰보단 공통적으로 적용할 수 있는 리뷰가 도움이 될 것 같아서 아래사항부터 차근차근 리팩터링하면 좋을 것 같습니다 :)  

개인적으로 [객체지향의 사실과 오해](https://m.yes24.com/Goods/Detail/18249021) 라는 책을 추천드려요! 객체지향적인 사고를 하시데 많은 도움이 될 겁니다 💪

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +    val userId: LiveData<Int> = _userId
해당 프로퍼티는 사용하고 있지 않는거 같습니다..!

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +    val friendsInfo: LiveData<List<GetFriendsResponse.Data>> = _friendsInfo
이렇게 필드를 구성하면 어떤 점에 장단점이 있었나요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +        if (userId == 0) {
매직넘버 상수화 부탁드립니다

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +        }
서버 통신에 실패했을 때 아무 대처를 하지 않고 있습니다..  
사용자에게 무언가 잘못 됐음을 알려야하지 않을까요??

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +class MainViewModel : ViewModel() {
동료 개발자가 MainXXX 라는 네이밍을 보고 어떤 화면인지 인지할 수 있을까요?!

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +        }
서버 통신에 실패했을 때 아무 대처를 하지 않고 있습니다..  
사용자에게 무언가 잘못 됐음을 알려야하지 않을까요??

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/myPage/MyPageScreen.kt
> +}
Composable 어노테이션을 붙이신 이유가 있을까요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/signUp/SignUpScreen.kt
뷰모델에 있어야할 정보가 아닐까요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +object NetworkModule {
NeworkModule 이라고 네이밍 하신 이유가 있을까요??   
해당 class 는 어떤 역할을 하고 있을까요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +        }
kotlin-serialization 의 Json 빌더 함수에는 다양한 옵션을 부여할 수 있습니다.    
그 중 `ignoreUnknownKeys` 사용하셨는데 해당 옵션을 추가하신 이유가 있을까요??

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +    private fun getLogOkHttpClient(): Interceptor {
해당 함수는 Interceptor를 반환해주고 있습니다.
getLogOkHttpClient 라는 네이밍이 맞을까요?! 🤔

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +                Log.d("Retrofit2", "CONNECTION INFO -> $message")
여기에 Log 를 추가한 이유가 궁금합니다..! (이건 정말 순수한 궁금증입니다.. 하하)

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +    fun provideRetrofit(url: String): Retrofit {
위에서는 `get` Prefix를 사용하셨는데 왜 여기서는 `provide` Prefix를 사용하셨나요?? 🤔  

네이밍에 대한 준서님 만의 기준이 있을까요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +    fun provideRetrofit(url: String): Retrofit {
url에 따라 동적으로 Retrofit 객체를 만드는 함수를 만드셨네요. 💯

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +}
```suggestion
    inline fun <reified T> create(url: String): T = provideRetrofit(url).create()
}
```

타입 클래스를 넘겨주지 않아도 됩니다.

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +}
by lazy 를 활용해볼 수 있을까요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +data class GetFriendsResponse(
Get 이라는 Prefix 가 붙은 이유를 여쭤볼 수 있을까요??

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +    val `data`: List<Data>,
저두요..! ㅋㅋㅋ  
혹시 tool을 사용하셨을 것 같다는 킹리적 갓심 🫢

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +    data class Data(
Data 라는 네이밍을 보고 동료 개발자가 이해할 수 있을까요?!

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetUserResponse.kt
> +data class GetUserResponse(
Get 이라는 Prefix 가 붙은 이유를 여쭤볼 수 있을까요??

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetUserResponse.kt
> +    val data: User? = defaultUser,
- default 값을 넣어주신 이유가 있을까요??
- default 값을 넣어주셨는데 nullable한 이유가 있을까요>?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/service/AuthService.kt
> +    suspend fun signUp(
코루틴 적용 💯

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/common/base/BaseFactory.kt
> +}
- BaseFactory 를 만드신 이유가 궁금합니다!  
- BaseFactory 라는 네이밍을 보고 어떤 객체를 만드는 class 인지 동료 개발자가 알 수 있을까요?

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/common/base/BaseFactory.kt
> +) : ViewModelProvider.Factory where T : ViewModel {
오 where 키워드를 아시는 걸로 보아 코틀린에 관심이 많으시군요 😸  

하지만, where 를 사용하신 이유가 있을까요?  

```suggestion
class BaseFactory<T: ViewModel>(
    private val creator: () -> T,
) : ViewModelProvider.Factory  {
```

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +import androidx.activity.ComponentActivity
ComponentActivity 와 AppCompatActivity 의 차이에 대해 알고 계실까요??

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +    Scaffold(bottomBar = { BottomNav(navController = navController) }) { paddingValues ->
Scaffold 를 사용하셨네요 💯

2024-05-05 19:07 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +                _friendsInfo.value = it.body()?.data ?: emptyList()
```suggestion
                _friendsInfo.value = it.body()?.data.orEmpty()
```

이런 확장 함수도 있답니다 🫢

2024-05-10 07:35 UTC, junseo511 reviewed
혼돈의 도가니같은 저희 미흡한 컴포즈 코드였을텐데 꼼꼼한 답변 감사드립니다 ‼️
앞으로도 잘부탁드려요 🤭

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
http or https‼️ 세미나때 배웠습니다 선생님~~~💩

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +object NetworkModule {
음,,, 독립적으로 네트워크 연결을 담당해주는 부분이라 그렇게 정했습니다...!
인터셉터로 로그 받기, Json 타입 변환, url 연결 등등 여러 역할을 하고 있습니다 🤔

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +    private fun getLogOkHttpClient(): Interceptor {
오...! 전혀 생각 안해본 부분인데 provide가 더 맞는거같아요

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +                Log.d("Retrofit2", "CONNECTION INFO -> $message")
서버와 통신을 할 때 편의성을 위해 추가했습니다!! 제대로 통신이 이루어지고 있는지, 어떤 데이터가 오는지 확인이 편해서 사용하는 편입니다 🤭

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +    fun provideRetrofit(url: String): Retrofit {
하하 get 다른 코드를 복붙한걸 이렇게 들킵니다 🥲

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +}
```kotlin
inline fun <reified T> create(url: String): T = provideRetrofit(url).create(T::class.java)
```
는 적어줘야 오류가 안나는군요!!!

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +    val `data`: List<Data>,
이에 대한 답변은 xml에 달았습니둥~~

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +}
오호 알아보겠습니다!! 아직 크게 안친한 친구여서요...! 인사만 하는 사이?

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +data class GetFriendsResponse(
친구목록을 받아오는 API 여서 GetFriends를 사용했는데 뭔가 더 기깔난 이름이 있을까요 🤔

저도 별로 안예쁘다고 생각했거든요

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetFriendsResponse.kt
> +    data class Data(
저는 서버에서 오는 네이밍을 최대한 따르는 편입니다...!

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetUserResponse.kt
> +data class GetUserResponse(
흠 두번째 보니까 역시 클래스 앞에 동사이름은 불편하긴 합니다~~🤣

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetUserResponse.kt
> +    val data: User? = defaultUser,
- 혹시 서버 통신에 실패했을 때 튕기지 않도록 하려고 넣었습니다...!
- 플러그인이 자동으로 추가했는데 그냥 지나친듯 합니다 🤔

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/common/base/BaseFactory.kt
> +) : ViewModelProvider.Factory where T : ViewModel {
좋은 지적 감사합니다!! 아직 전 제너릭이랑 안친한 것 같아요 🥲

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/common/base/BaseFactory.kt
> +}
- 반복되는 코드를 줄여보려고 했습니다!
- 이렇게 말씀하시니 뭔가 번뜩하는군요!! 좋습니다 👍

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +import androidx.activity.ComponentActivity
컴포즈를 더 쉽게 사용할 수 있는 액티비티,,,! 로 알고 잇습니다 😇

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +fun ProfilePicture(url: String) {
ㅈㅅ Image 쓸래요

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +    val userId: LiveData<Int> = _userId
매의 눈이신가요...! 감사합니다 (꾸벅)

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +class MainViewModel : ViewModel() {
이 부분은 저도 고민입니다...! CommonViewModel로 이름을 바꿀까 싶기도 하구요!

다른 뷰모델 사용법도 있어서 그 방법을 적용해볼까도 생각중입니당

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +    val friendsInfo: LiveData<List<GetFriendsResponse.Data>> = _friendsInfo
정확히 어떤 부분을 말씀하시는 건가요?!

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +        }
이 부분에 대해서 실패 로직이 아직 없네요 😅 추후 UiState를 과제로 다루게 된다면 도입하겠습니다!!

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +                _friendsInfo.value = it.body()?.data ?: emptyList()
아악 이 리뷰 또받아버렸네요!! 이런 😦

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/myPage/MyPageScreen.kt
> +}
아 실수인 것 같습니다...! 아직 컴포즈 함수분리가 어색하네요 🥲

2024-05-10 07:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/feature/signUp/SignUpScreen.kt
입력하는 정보도 viewModel로 가야하나요...?!

2024-05-13 03:13 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +    val friendsInfo: LiveData<List<GetFriendsResponse.Data>> = _friendsInfo
백킹프로퍼티라는 키워드를 드리겠습니다 :D

2024-05-13 03:16 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/signUp/SignUpScreen.kt
뷰가 상태를 홀딩하고 있는데요.
Viewmodel 의 역할이 무엇인지 고민해보셨으면 좋겠습니다 🙂

2024-05-13 03:22 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +                Log.d("Retrofit2", "CONNECTION INFO -> $message")
해당 코드없이
로깅인터셉터를 추가해도 어떤 데이터가 오는지 볼 수 있지않나요??

해당 코드를 추가하면 더 명확하게 볼수있는걸까요??

2024-05-13 03:26 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/common/base/BaseFactory.kt
> +) : ViewModelProvider.Factory where T : ViewModel {
제네릭이 많이 어렵지만
Kotlin/Java 개발자라면 필수적으로 학습해야할 문법이라고 생각해요!!

만약, 학습하시다가 궁금한 점이 생기시면
Discord DM 으로 언제든 물어봐주세요😉

2024-05-13 03:27 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeScreen.kt
> +import androidx.activity.ComponentActivity
이 부분은 추후 학습하셨으면 좋겠습니다 😉
내부 코드를 직접 보는것도 방법입니다!!

2024-05-13 03:31 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +    private fun getLogOkHttpClient(): Interceptor {
provide 가 왜 적절하다고 생각하시는지 궁금하군요..!

2024-05-13 03:34 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/feature/main/MainViewModel.kt
> +class MainViewModel : ViewModel() {
CommonViewModel도 마찬가지입니다..!
해당 뷰모델이 모든 곳에서 공통적으로 사용되는 뷰모델이 아닙니다!!

2024-05-13 03:35 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/remote/response/GetUserResponse.kt
> +    val data: User? = defaultUser,
디폴트 값을 넣어준다고 서버통신 실패 핸들링이 되진 않습니다..!

이 부분은 추후 학습해보시죠 🙃

2024-05-13 03:46 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/data/NetworkModule.kt
> +object NetworkModule {
NetworkModule 클래스는 외부(이 클래스를 사용하는 곳)에서 보면 레트로핏을 만드는 class로 보입니다.

확장성과 유지보수를 위해 class 분리를 해볼까요??

해당 코멘트는 객체지향적인 사고가 자리잡혀 있지 않다면 이해하기 힘드실거에요..
일단 넘어갑시다 🫠

2024-05-24 05:04 UTC, merged